#!/bin/bash
MODEL="sonar-pro"
SEARCH_CONTEXT_SIZE="high"
BASE_URL="https://api.perplexity.ai"
API_KEY=$PERPLEXITY_API_KEY
AI="Perplexity"

# Error trapper
trap 'echo "Error on line $LINENO"' ERR

get_new_history_file() {
  HISTORY="$HOME/.perplexity-auto-history-$(date +%Y-%m-%d-%H-%M-%S)"
}

while getopts 'orhdpu:lLnrRsc:v' opt; do
  case "$opt" in
    c)
      BASE_URL="https://api.anthropic.com/v1"

      if [ "$OPTARG" == "3.5" ]; then
        MODEL="claude-3-5-haiku-latest"
      else
        MODEL="claude-3-7-sonnet-latest"
      fi

      SEARCH_CONTEXT_SIZE=""
      API_KEY=$CLAUDE_API_KEY
      AI="Claude"
      ;;
    h)
      SEARCH_CONTEXT_SIZE="high"
      ;;
    p)
      MODEL="sonar-pro"
      ;;
    d)
      MODEL="sonar-deep-research"
      SEARCH_CONTEXT_SIZE=""
      ;;
    r)
      MODEL="sonar-reasoning"
      ;;
    R)
      MODEL="sonar-reasoning-pro"
      ;;
    u)
      HISTORY="$HOME/.perplexity-history-$OPTARG"
      ;;
    s)
      HISTORY=$(ls ~/.perplexity-history-* | gum filter)
      if [ -z "$HISTORY" ]; then
        echo "No history file selected"
        exit 1
      fi
      ;;
    l)
      ls ~/.perplexity-history-* 2> /dev/null
      ;;
    n)
      get_new_history_file
      ;;
    L)
      ls ~/.perplexity-history-* 2> /dev/null
      ls ~/.perplexity-auto-history-* 2> /dev/null
      ;;
    v)
      VOICE="true"
      ;;
    o)
      READ="true"
      ;;
    \?)
      gum format "Invalid option: -$OPTARG"
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

default_history() {
  if stat -t ~/.perplexity-auto-history-* >/dev/null 2>&1; then
    # get most recent file matching ~/.perplexity-history-*
    HISTORY=$(ls -t ~/.perplexity-auto-history-* | head -n 1)
    MODIFIED_AGO="$(( ($(date +%s) - $(stat $HISTORY -c %Y)) / 60 ))"

    if [ "$MODIFIED_AGO" -gt 10 ]; then
      get_new_history_file
    fi
  else
    get_new_history_file
  fi
}

load() {
  gum spin --spinner dot --title "$AI is thinking..." -- curl "$@"
}

if [ -z "$HISTORY" ]; then
  default_history
fi

gum format "Using history file: $HISTORY"
touch "$HISTORY"

CONTENT=$(echo "$@" | jq -Rsa .)

if [ -n "$VOICE" ]; then
  arecord -f dat voice.wav >/dev/null 2>&1
  RES=$(load --silent https://api.openai.com/v1/audio/transcriptions \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "Content-Type: multipart/form-data" \
    -F file="@voice.wav" \
    -F model="whisper-1")
  CONTENT=$(echo "$RES" | jq -r ".text")
  echo "You said: $CONTENT"
fi

PROMPT="{
  \"role\": \"user\",
  \"content\": $CONTENT
}"

INITIAL_PROMPT="Be precise and concise. Do not add disclaimer as they cause me a great deal of inconfort."
echo "$PROMPT"

DATA="
{
  \"model\": \"$MODEL\",
  $([[ $SEARCH_CONTEXT_SIZE != "" ]] && echo "\"search_context_size\": \"$SEARCH_CONTEXT_SIZE\"," || echo "")
  \"messages\": [
    {
      \"role\": \"system\",
      \"content\": \"$INITIAL_PROMPT\"
    },
    $(cat "$HISTORY")
    $PROMPT
  ]
}"

RESPONSE=$(load --silent --location "$BASE_URL/chat/completions" \
                --header 'accept: application/json' \
                --header 'content-type: application/json' \
                --header "Authorization: Bearer $API_KEY" \
                --data "$DATA")

if echo "$RESPONSE" | jq -e ".error"> /dev/null 2>&1;
then
  echo "$RESPONSE" | jq ".error" > /dev/stderr
  exit 1
fi

if [ "$AI" == "Perplexity" ]; then
  # To show citation like "[1] website" we need to put number between [] and do +1 from the key
  CITATIONS=$(echo "$RESPONSE" | jq -r '.citations | to_entries | map("[" + ((.key + 1) | tostring) + "] " + .value) | join("\n")')
  echo "# Citations" | glow
  # Disable width wrapping
  echo "$CITATIONS" | glow --width 0
fi

CONTENT=$(echo "$RESPONSE" | jq -r '.choices.[0].message.content')

echo "# Results" | glow
# Disable width wrapping
echo "$CONTENT" | glow --width 0

MESSAGE=$(echo "$RESPONSE" | jq -r '.choices.[0].message')

if [ -n "$READ" ]; then
  CONTENT_SINGLE_LINE=$(echo "$CONTENT" | tr '\n' ' ')
  DATA='
    {
      "model": "gpt-4o-mini-tts",
      "input": "'"$CONTENT_SINGLE_LINE"'",
      "voice": "nova"
    }
  '

  load --location "https://api.openai.com/v1/audio/speech" \
      --header "Authorization: Bearer $OPENAI_API_KEY" \
      --header "Content-Type: application/json" \
      --data "$DATA" --output /tmp/speech.mp3

  mpg123 -q /tmp/speech.mp3
  mv /tmp/speech.mp3 /tmp/old-speech.mp3
fi

echo "$PROMPT,$MESSAGE," >> "$HISTORY"
